version: "3.8"

volumes:
  pia:
  piaetc:

services:
  pia:
    image: ghcr.io/double16/pia-container:main
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    dns:
      - 209.222.18.222
      - 209.222.18.218
    volumes:
      - pia:/config
      - piaetc:/opt/piavpn/etc

  kali:
    build: kali
    restart: unless-stopped
    network_mode: "service:pia"
    depends_on:
      - pia

# docker exec -it --user 99:100 kali-kali-1 /usr/bin/zsh
