volumes:
  pia:
  piaetc:
  home:

services:
  pia:
    image: ghcr.io/double16/pia-container:main
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - MKNOD
    devices:
      - /dev/net/tun
    privileged: true
    dns:
      - 209.222.18.222
      - 209.222.18.218
    volumes:
      - pia:/config
      - piaetc:/opt/piavpn/etc

  kali:
    build: kali
    restart: unless-stopped
    network_mode: "service:pia"
    depends_on:
      - pia
    volumes:
      - home:/home/kali

  zap:
    build: zap
    restart: unless-stopped
    network_mode: "service:pia"
    depends_on:
      - pia
